name: Deploy Frontend to Azure Static Web Apps (Development)

on:
  push:
    branches:
      - main
      - feat/github-actions-frontend
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend-to-dev.yml'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./frontend

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install packages
        run: npm install

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_FRONTEND_DEPLOY_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "./frontend"
          output_location: "dist"
          app_build_command: "npm run build"
